pluginManagement {
    repositories {
        //mavenLocal()
        //maven { url = '...' }
        gradlePluginPortal()
        mavenCentral()
    }
}

buildCache {
    local {
        directory = new File(rootDir, 'build-cache')
    }
}

rootProject.name = 'MsAuth'

include ':applications:app-service'
include ':domain:model'
include ':domain:usecase'
include ':infrastructure:driven-adapters:r2dbc-postgresql'
include ':infrastructure:entry-points:reactive-web'
include ':infrastructure:driven-adapters:security-provider'