server:
  port: 8080
springdoc:
  packages-to-scan: co.com.bancolombia.api
spring:
  application:
    name: "MsAuth"
  main:
    web-application-type: reactive
adapters:
  r2dbc:
    host: localhost
    port: 5432
    database: db_auth_ms
    schema: public
    username: dbeaver
    password: 12345
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true

cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"