server:
  port: 8080

spring:
  application:
    name: "ms-authentication"
  main:
    web-application-type: reactive

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  info:
    title: "Microservicio de Autenticación"
    description: "API REST para la gestión de usuarios, incluyendo registro y consulta."
    version: "1.0.0"

adapters:
  r2dbc:
    host: localhost
    port: 5432
    database: db_auth_ms
    schema: public
    username: dbeaver
    password: 12345

security:
  jwt:
    secret: "${JWT_SECRET:EstaEsUnaClaveSecretaPorDefectoNoSeguraParaDesarrollo}"
    expiration: 3600

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true

cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"